---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spotify-app
  labels:
    app: spotify-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spotify-app
  template:
    metadata:
      labels:
        app: spotify-app
    spec:
      containers:
        - name: spotify-container
          image: 970547377227.dkr.ecr.us-east-1.amazonaws.com/spotify-clone:latest
          ports:
            - containerPort: 8080
