---
apiVersion: v1
kind: Service
metadata:
  name: spotify-app
  labels:
    app: spotify-app
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 3000
  selector:
    app: spotify-app
  type: LoadBalancer
